#!/bin/bash

##########################################
#   Author: Jakub Frąckiewicz            #
#   Github: https://github.com/Lechnio   #
##########################################

# Remove
(alias | grep -q "alias ll") && unalias ll
(alias | grep -q "alias la") && unalias la
(alias | grep -q "alias grep") && unalias grep

# Base
alias ll='ls -l'
alias la='ls -lA'
alias grep='grep --color=auto'
alias greph='history | grep'
alias cls='clear'
alias untar='tar -xvf'
alias untargz='tar -zxvf'
alias untarbz='tar -jxvf'
alias cds='EASY_SAVED_PWD="$(pwd)"'
alias cdb='cd "$EASY_SAVED_PWD"'
alias findd='find . -name'
alias lsport='lsof -i -P -n'
alias :q='exit'

# Git
alias gitst='git status'
alias gitbr='git branch'
alias gitlog='git log --all --decorate --oneline --graph'
alias gitreset='git reset --soft HEAD~1'
alias gitdiff='git diff --staged'
